### ISSUE TITLE
Write a program to control the robot.

### ISSUE THREAD

**Issue by shallwing** [RIF-Robotics/ar3_ros#3]
Hello, do you know how to using Python code to control the arm rather than using GUI in rviz?

**Comment by SyllogismRXS** [comment]
This repo provides MoveIt2 interfaces for the AR3. MoveIt2 currently only supports a [C++ interface](https://moveit.picknik.ai/humble/doc/tutorials/your_first_project/your_first_project.html#). There are some PRs to support a Python interface to MoveIt2: https://github.com/ros-planning/moveit2/issues/1279 and https://github.com/ros-planning/moveit2/pull/1546
